[package]
name = "simple_axum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iis = { version = "0.1.0" }
axum = { version = "0.7.5" }
anyhow = { version = "1.0.75" }
tokio = { version = "1.34.0", features = ["full"] }
